// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXK5Y3SNFjSBMja8xUCK30v9a_OEO7nCU',
    appId: '1:1041518236915:web:c60961934ec949e3651386',
    messagingSenderId: '1041518236915',
    projectId: 'gsrwithuv',
    authDomain: 'gsrwithuv.firebaseapp.com',
    databaseURL: 'https://gsrwithuv-default-rtdb.firebaseio.com',
    storageBucket: 'gsrwithuv.appspot.com',
    measurementId: 'G-TZE9X9ETRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDiHV-1Fb47thARVXTCVJB09IFOUAS7DY',
    appId: '1:1041518236915:android:af9ced1327dd8cca651386',
    messagingSenderId: '1041518236915',
    projectId: 'gsrwithuv',
    databaseURL: 'https://gsrwithuv-default-rtdb.firebaseio.com',
    storageBucket: 'gsrwithuv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuGKH9BQCD6BiIswdPbygvJDx03a5KFbY',
    appId: '1:1041518236915:ios:8b898a8f8416ecec651386',
    messagingSenderId: '1041518236915',
    projectId: 'gsrwithuv',
    databaseURL: 'https://gsrwithuv-default-rtdb.firebaseio.com',
    storageBucket: 'gsrwithuv.appspot.com',
    iosClientId: '1041518236915-e05bqkv6at0ne8cjmlf0qmqdjec347h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.hydrated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuGKH9BQCD6BiIswdPbygvJDx03a5KFbY',
    appId: '1:1041518236915:ios:8b898a8f8416ecec651386',
    messagingSenderId: '1041518236915',
    projectId: 'gsrwithuv',
    databaseURL: 'https://gsrwithuv-default-rtdb.firebaseio.com',
    storageBucket: 'gsrwithuv.appspot.com',
    iosClientId: '1041518236915-e05bqkv6at0ne8cjmlf0qmqdjec347h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.hydrated',
  );
}
